// <auto-generated />
namespace Web.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitalCharges_Per_KM_Hour_Rate_KM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalCharges_Per_KM_Hour_Rate_KM));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030714380_InitalCharges_Per_KM_Hour_Rate_KM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
